---
title: "Programming with R"
author: "Nathan Young"
date: "4/19/2021"
output:
  html_document:
    toc: yes
    toc_float:
      toc_collapsed: yes
    theme: spacelab
  pdf_document:
    toc: yes
---

## Control Structures

#### if
```{r if eval=FALSE}
if(<condition>) {
  ## do something
} else {
  ## do something
}
if(<condition1>) {
  ## do something
} else if(<condition2>) {
  ## do something different
} else {
  ## do something different
}
```

```{r}
if(x > 3) {
  y <- 10
} else {
  y <- 0
}
y <- if (x > 3) {
  10
} else {
  0
}
```

#### For loops
```{r for loops}
for (i in 1:10) {
  print(i)
}
x <- c("a", "b", "c", "d")
for (i in 1:4) {
  print(x[i])
}
for (i in seq_along(x)) {
  print(x[i])
}
for (letter in x) {
  print(letter)
}
for (i in 1:4)
  print(x[i]
  )
```

#### Nested for loops
```{r}
x <- matrix(1:6, 2, 3)

for (i in seq_len(nrow(x))) {
  for (j in seq_len(ncol(x))) {
    print(x[i, j])
  }
}
```

#### While loops
```{r while loops}
count <- 0
while (count < 10) {
  print(count)
  count <- count + 1
}

x <- 5
while (x >= 3 && x <= 10) {
  print(x)
  coin <- rbinome(1, 1, 0.5)
  
  if (coint == 1) {
    ## random walk
    z <- z + 1
  } else {
    z <- z - 2
  }
}
```

#### Repeat, Next, Brake
```{r repeat}
x0 <- 1
tol <- 1e-8

repeat {
  x1 <- computeEstimate()
  if (abs(x1 - x0) < tol) {
    break
  } else {
    x0 <- x1
  }
}
```

```{r next, return, execute=False}
for (i in 1:100) {
  if (i <= 20) {
    ## skip the first 20 iterations
    next
  }
  ## do something here
}
```

## Dates and Times

#### Dates in R

```{r Dates in R}
x <- as.Date("1970-01-01")
x
unclass(x)
unclass(as.Date("1970-01-02"))
```

#### Times in R
```{r Times in R}
x <- Sys.time()
x
p <- as.POSIXlt(x)
names(unclass(p))
p$sec
```
```{r}
x <- Sys.time()
x
unclass(x)
x$sec
p <- as.POSIXlt(x)
p$sec
```
```{r}
datestring <- c("January 10, 2012 10:40", "December 9, 2011 9:10")
x <- strptime(datestring, "%B %d, %Y %H:%M")
x
class(x)
```

#### Operations on Dates and Times
```{r Operations on Dates and Times}
x <- as.Date("2012-01-01")
y <- strptime("9 Jan 2011 11:34:21", "%d %b %Y %H:%M:%S")
x - y
x <- as.POSIXlt(x)
x - y
```
```{r}
x <- as.Date("2012-03-01") 
y <- as.Date("2012-02-28")
x - y
x <- as.POSIXct("2012-10-25 01:00:00")
y <- as.POSIXct("2012-10-25 06:00:00", tz = "GMT")
y - x


```
